# This Program shows how to Handle Errors using the Try and Except Statementsprint('Program shows how to Handle Errors using the Try and Except Statements')def myFunction(num):	try:			return 30/num	except:		print('Trying to Divide by Zero')print(myFunction(3))print(myFunction(30))print(myFunction(0))  # Dividing by Zero will lead to DivideByZero Error which will be handled by the except blockprint(myFunction(10)) 	